In [ ]:
print("Hello world")

Hello world


In [ ]:
x=5
m=6
y="9"
z="5"
print(type(x))
print(type(y))
print(x+m)
print(y+z)
print(len(y))
print(z[0])

<class 'int'>
<class 'str'>
11
95
1
5


In [ ]:
#typecasting
a=int(z)
print(a+m)

11


In [ ]:
#list
l1=['hi',1,7,"list",6.7,9.5,[3,89,"hello"]]
l2=l1[6][2]
print(l2)
length=len(l1)
print(length)

hello
7


In [ ]:
nums=[]
nums.append(21)
nums.append(40.5)
nums.append("String")
print(nums)

[21, 40.5, 'String']


In [ ]:
#tuple
t1=(1,2,3,4,5,6,7,8)
print(t1)

(1, 2, 3, 4, 5, 6, 7, 8)


In [ ]:
#dictionary
d1={"Name":"Esh","Age":"18","Proff":"Student"}
print(d1)
print(type(d1))
print(d1.keys())
print(d1.values())
print(d1.items())
print(d1["Name"])

{'Name': 'Esh', 'Age': '18', 'Proff': 'Student'}
<class 'dict'>
dict_keys(['Name', 'Age', 'Proff'])
dict_values(['Esh', '18', 'Student'])
dict_items([('Name', 'Esh'), ('Age', '18'), ('Proff', 'Student')])
Esh


In [ ]:
num1=int(input("Enter num1"))
num2=int(input("Enter num2"))
num3=num1+num2
print("Product:",num3)

num1=int(input("Enter a number:"))
if num1>12:
  print("Number is greater than 12")
else:
  print("Number is smaller than 12")


Enter num15
Enter num23
Product: 8
Enter a number:15
Number is greater than 12


In [ ]:
#array
import numpy as np

#creating array object
arr = np.array([[1,2,3],
              [4,5,6]] )

#printing type of array object
print("Array is of type: ", type(arr))

#printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)

#printing shape of array
print("Shape of array: ", arr.shape)

#printing size of array
print("Size of array: ", arr.size)

#printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int64


In [ ]:
import numpy as np

#creating a rank 1 array
arr = np.array([1, 2, 3])
print("Array with Rank 1: \n",arr)

# Creating a rank 2 array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Array with Rank 2: \n", arr)

# Creating an array from tuple
arr = np.array((1, 3, 2))
print("\nArray created using passed tuple:\n", arr)

Array with Rank 1: 
 [1 2 3]
Array with Rank 2: 
 [[1 2 3]
 [4 5 6]]

Array created using passed tuple:
 [1 3 2]


In [ ]:
import numpy as np

arr = np.array([2, 4, 6, 8, 10])

#creating copy of array
c = arr.copy()

# both arr and c have different id
print("id of arr", id(arr))
print("id of c", id(c))

# changing original array will not effect copy
arr[0] = 12

# printing array and copy
print("original array- ", arr)
print("copy- ", c)


id of arr 135670772224752
id of c 135670385795568
original array-  [12  4  6  8 10]
copy-  [ 2  4  6  8 10]


In [ ]:
#lets define our function
#parameters: input array

def sum(array):

  #set variable for our final answer
  sum = 0

  #parse through our array
  for i in array:

    #countinously add current element to final sum
    sum += i

  #return sum
  return sum

#create a test array
testArray = [1, 3, 35, 92, 29, 48, 20.3]

#test our function
print('The sum of your number is ' + str(sum(testArray)))


The sum of your number is 228.3


In [ ]:
import numpy as np

#create a sequence of integers from 10 to 1 with a step of -2
a = np.arange(10, 1, -2)
print("\n A sequential array with a negative step: \n",a)

# Indexes are specified inside the np.array method
newarr = a[np.array([3, 1, 2 ])]
print("\n Elements at these indices are:\n",newarr)



 A sequential array with a negative step: 
 [10  8  6  4  2]

 Elements at these indices are:
 [4 8 6]


In [ ]:
#the result includes the start index, but excludes the end index
import numpy as np

#create an array
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5]) #start:stop
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2]) #start:stop:jump
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [11]:
import numpy as np

#create an array
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [12]:
#The copy SHOULD NOT be affected by the changes made to the original array.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy() #copying an array
arr[0] = 42

print(arr) #printing original array
print(x) #printing copy of array

[42  2  3  4  5]
[1 2 3 4 5]


In [14]:
#the view SHOULD be affected by the changes made to the original array.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [16]:
#to check if array owns its data
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [17]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape) #displays the dimension of an array


(2, 4)


In [18]:
#create an array with 5 dimensions using ndmin
#using a vector with values 1,2,3,4 and verify that last dimension has value 4:

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [19]:
#Convert the following 1-D array with 12 elements into a 2-D array

#The outermost dimension will have 4 arrays, each with 3 elements:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

#The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

newarr = arr.reshape(2, 3, 2)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [20]:
# Python code to demonstrate matrix operations
# add(), subtract() and divide()

#importing numpy for matrix operations
import numpy

# initializing matrices
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])

# using add() to add matrices
print ("The element wise addition of matrix is : ")
print (numpy.add(x,y))

# using subtract() to subtract matrices
print ("The element wise subtraction of matrix is : ")
print (numpy.subtract(x,y))

# using divide() to divide matrices
print ("The element wise division of matrix is : ")
print (numpy.divide(x,y))


The element wise addition of matrix is : 
[[ 8 10]
 [13 15]]
The element wise subtraction of matrix is : 
[[-6 -6]
 [-5 -5]]
The element wise division of matrix is : 
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]


In [21]:
#dictionaries
import pandas

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pandas.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [22]:
#Pandas package can be referred to as pd instead of pandas.
import pandas as pd

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pd.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [23]:
#The version string is stored under __version__ attribute.
import pandas as pd

print(pd.__version__)

2.0.3


In [24]:
#A Pandas Series is like a column in a table.

#It is a one-dimensional array holding data of any type.
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar)

#Return the first value of the Series:

print(myvar[0])

0    1
1    7
2    2
dtype: int64
1


In [25]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"]) #the indexes are x,y,z instead of the default 0,1,2...

print(myvar)

print(myvar["y"])

x    1
y    7
z    2
dtype: int64
7


In [26]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df)

#refer to the row index:
print(df.loc[0])
#Returns a pandas series


#use a list of indexes:
print(df.loc[[0, 1]])
#When using [], the result is a Pandas DataFrame.

   calories  duration
0       420        50
1       380        40
2       390        45
calories    420
duration     50
Name: 0, dtype: int64
   calories  duration
0       420        50
1       380        40


In [28]:
import pandas as pd

df = pd.read_csv('Data.csv')

print(df.to_string())
#use to_string() to print the entire DataFrame.

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [31]:
import pandas as pd

df = pd.read_csv('Iris.csv')

print(df)
#If you have a large DataFrame with many rows, Pandas will only return the first 5 rows, and the last 5 rows

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  

In [32]:
import pandas as pd

print(pd.options.display.max_rows)
#The number of rows returned is defined in Pandas option settings.

#You can check your system's maximum rows with the pd.options.display.max_rows statement.

60


In [33]:
import pandas as pd

pd.options.display.max_rows = 9999

df = pd.read_csv('Iris.csv')

print(df)

print(pd.options.display.max_rows)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
5      6            5.4           3.9            1.7           0.4   
6      7            4.6           3.4            1.4           0.3   
7      8            5.0           3.4            1.5           0.2   
8      9            4.4           2.9            1.4           0.2   
9     10            4.9           3.1            1.5           0.1   
10    11            5.4           3.7            1.5           0.2   
11    12            4.8           3.4            1.6           0.2   
12    13            4.8           3.0            1.4           0.1   
13    14            

In [34]:
#Load a Python Dictionary into a DataFrame   JSON= Python Dictionary
import pandas as pd

data = {
  "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127
  },
  "Calories":{
    "0":409,
    "1":479,
    "2":340,
    "3":282,
    "4":406,
    "5":300
  }
}

df = pd.DataFrame(data)

print(df)


   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300


In [35]:
# importing the module
import pandas as pd

# creating the first DataFrame
df1 = pd.DataFrame({"fruit" : ["apple", "banana", "avocado"],
					"market_price" : [21, 14, 35]})
display("The first DataFrame")
display(df1)

# creating the second DataFrame
df2 = pd.DataFrame({"fruit" : ["banana", "apple", "avocado"],
					"wholesaler_price" : [65, 68, 75]})
display("The second DataFrame")
display(df2)

# joining the DataFrames
display("The merged DataFrame")
pd.merge(df1, df2, on = "fruit", how = "inner")
# how : {‘left’, ‘right’, ‘outer’, ‘inner’}, default ‘inner’


'The first DataFrame'

fruit  market_price
0    apple            21
1   banana            14
2  avocado            35

'The second DataFrame'

fruit  wholesaler_price
0   banana                65
1    apple                68
2  avocado                75

'The merged DataFrame'

fruit  market_price  wholesaler_price
0    apple            21                68
1   banana            14                65
2  avocado            35                75

In [38]:
#Merging two data frames with different number of elements
# importing the module
import pandas as pd

# creating the first DataFrame
df1 = pd.DataFrame({"fruit" : ["apple", "banana",
                               "avocado", "grape"],
                    "market_price" : [21, 14, 35, 38]})
display("The first DataFrame")
display(df1)

# creating the second DataFrame
df2 = pd.DataFrame({"fruit" : ["apple", "banana", "grape"],
                    "wholesaler_price" : [65, 68, 71]})
display("The second DataFrame")
display(df2)

# joining the DataFrames
# here both common DataFrame elements are in df1 and df2,
# so it extracts apple, banana, grapes from df1 and df2.
display("The merged DataFrame")
pd.merge(df1, df2, on = "fruit", how = "inner")

pd.merge(df1, df2, on = "fruit", how = "outer")

'The first DataFrame'

fruit  market_price
0    apple            21
1   banana            14
2  avocado            35
3    grape            38

'The second DataFrame'

fruit  wholesaler_price
0   apple                65
1  banana                68
2   grape                71

'The merged DataFrame'

fruit  market_price  wholesaler_price
0    apple            21              65.0
1   banana            14              68.0
2  avocado            35               NaN
3    grape            38              71.0

In [40]:
# Pandas dataframe.groupby() function is used to split the data into groups based on some criteria.
# Pandas objects can be split on any of their axes.
# importing pandas as pd
import pandas as pd

# Creating the dataframe
df = pd.read_csv("Iris.csv")

# Print the dataframe
print(df.head())    #Returns  top n (5 by default) rows of a data frame or series.

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa


In [41]:
# applying groupby() function to
# group the data on team value.
gk = df.groupby('Species')

# Let's print the first entries
# in all the groups formed.
gk.first()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Species                                                                       
Iris-setosa        1            5.1           3.5            1.4           0.2
Iris-versicolor   51            7.0           3.2            4.7           1.4
Iris-virginica   101            6.3           3.3            6.0           2.5

In [43]:
# Finding the values contained in the "Iris-versicolor" group
gk.get_group('Iris-versicolor')

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
50   51            7.0           3.2            4.7           1.4   
51   52            6.4           3.2            4.5           1.5   
52   53            6.9           3.1            4.9           1.5   
53   54            5.5           2.3            4.0           1.3   
54   55            6.5           2.8            4.6           1.5   
55   56            5.7           2.8            4.5           1.3   
56   57            6.3           3.3            4.7           1.6   
57   58            4.9           2.4            3.3           1.0   
58   59            6.6           2.9            4.6           1.3   
59   60            5.2           2.7            3.9           1.4   
60   61            5.0           2.0            3.5           1.0   
61   62            5.9           3.0            4.2           1.5   
62   63            6.0           2.2            4.0           1.0   
63   64            6.1           2.9            4.7           1.4   
64   65            5.6           2.9            3.6           1.3   
65   66            6.7           3.1            4.4           1.4   
66   67            5.6           3.0            4.5           1.5   
67   68            5.8           2.7            4.1           1.0   
68   69            6.2           2.2            4.5           1.5   
69   70            5.6           2.5            3.9           1.1   
70   71            5.9           3.2            4.8           1.8   
71   72            6.1           2.8            4.0           1.3   
72   73            6.3           2.5            4.9           1.5   
73   74            6.1           2.8            4.7           1.2   
74   75            6.4           2.9            4.3           1.3   
75   76            6.6           3.0            4.4           1.4   
76   77            6.8           2.8            4.8           1.4   
77   78            6.7           3.0            5.0           1.7   
78   79            6.0           2.9            4.5           1.5   
79   80            5.7           2.6            3.5           1.0   
80   81            5.5           2.4            3.8           1.1   
81   82            5.5           2.4            3.7           1.0   
82   83            5.8           2.7            3.9           1.2   
83   84            6.0           2.7            5.1           1.6   
84   85            5.4           3.0            4.5           1.5   
85   86            6.0           3.4            4.5           1.6   
86   87            6.7           3.1            4.7           1.5   
87   88            6.3           2.3            4.4           1.3   
88   89            5.6           3.0            4.1           1.3   
89   90            5.5           2.5            4.0           1.3   
90   91            5.5           2.6            4.4           1.2   
91   92            6.1           3.0            4.6           1.4   
92   93            5.8           2.6            4.0           1.2   
93   94            5.0           2.3            3.3           1.0   
94   95            5.6           2.7            4.2           1.3   
95   96            5.7           3.0            4.2           1.2   
96   97            5.7           2.9            4.2           1.3   
97   98            6.2           2.9            4.3           1.3   
98   99            5.1           2.5            3.0           1.1   
99  100            5.7           2.8            4.1           1.3   

            Species  
50  Iris-versicolor  
51  Iris-versicolor  
52  Iris-versicolor  
53  Iris-versicolor  
54  Iris-versicolor  
55  Iris-versicolor  
56  Iris-versicolor  
57  Iris-versicolor  
58  Iris-versicolor  
59  Iris-versicolor  
60  Iris-versicolor  
61  Iris-versicolor  
62  Iris-versicolor  
63  Iris-versicolor  
64  Iris-versicolor  
65  Iris-versicolor  
66  Iris-versicolor  
67  Iris-versicolor  
68  Iris-versicolor  
69  Iris-versicolor  
70  Iris-versicolor  
7

In [44]:
#Indentation
j = 1

while(j<= 5):
	print(j)
	j = j + 1


1
2
3
4
5
